Students/urls.py
from django.urls import path
from . import views

app_name = 'Students' # он же namespace='Students' в config.urls

urlpatterns = [
    # FBV Адреса
    path('show_data/', views.show_data, name='show_data'),
    path('submit_data/', views.submit_data, name='submit_data'),
    path('item/<int:item_id>', views.show_item, name='show_item'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('index/', views.index, name='index'),
    path('student_detail/<int:student_id>/', views.student_detail, name='student_details'),
    path('students/', views.student_list, name='student_list'),


    path('student_create/', views.StudentCreateView.as_view(), name='student_create'),
    path('student_update/<int:pk>/', views.StudentUpdateView.as_view(), name='student_update'),

    # CBV Адреса
    path('mymodel/list/', views.MyModelListView.as_view(), name='mymodel_list'),
    path('mymodel/create/', views.MyModelCreateView.as_view(), name='mymodel_create'),
    path('mymodel/detail/<int:pk>', views.MyModelDetailView.as_view(), name='mymodel_detail'),
    path('mymodel/update/<int:pk>', views.MyModelUpdateView.as_view(), name='mymodel_update'),
    path('mymodel/delete/<int:pk>', views.MyModelDeleteView.as_view(), name='mymodel_delete'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Students/', include('Students.urls', namespace='Students')),    # таким образом мы подключаем .urls с нешего приложения
    path('library/', include('library.urls', namespace='library')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

"""
Определяет маршрутизацию для вашего проекта, 
связывая URL-адреса с соответствующими контроллерами (views)
"""

Students/models.py
from django.db import models


class MyModel(models.Model):
    """Класс для CBV модели"""
    name = models.CharField(max_length=300)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Group(models.Model):
    group_name = models.CharField(max_length=100, verbose_name='Название группы')

    def __str__(self):
        return f'{self.group_name}'

    class Meta:
        verbose_name = 'группа'
        verbose_name_plural = 'группы'
        ordering = ['group_name']


def get_default_group():
    return Group.objects.get_or_create(group_name='Default Group')[0].id


class Student(models.Model):
    FIRST_YEAR = 'first'
    SECOND_YEAR = 'second'
    THIRD_YEAR = 'third'
    FOURTH_YEAR = 'fourth'

    YEAR_IN_SCHOOL_CHOICES = [
        (FIRST_YEAR, 'first'),
        (SECOND_YEAR, 'second'),
        (THIRD_YEAR, 'third'),
        (FOURTH_YEAR, 'fourth'),
    ]

    first_name = models.CharField(max_length=150, verbose_name='Имя')
    last_name = models.CharField(max_length=150, verbose_name='Фамилия')
    email = models.EmailField()
    # description = models.TextField(null=True, blank=True)
    year = models.CharField(max_length=6, choices=YEAR_IN_SCHOOL_CHOICES, default=FIRST_YEAR, verbose_name='Курс')
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='Students', default=get_default_group)
    enrollment_date = models.DateField()

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        verbose_name = 'студент'
        verbose_name_plural = 'студенты'
        ordering = ['last_name']

    # first_name = models.CharField(max_length=150, verbose_name="Имя")
    # last_name = models.CharField(max_length=150, verbose_name="Фамилия", unique=True)
    #
    # age = models.IntegerField(help_text='Введите возраст студента')
    # is_active = models.BooleanField(default=True)
    # description = models.TextField(null=True, blank=True)
    # created_at = models.DateTimeField(auto_now_add=True)
    # image = models.ImageField(upload_to='photos/', verbose_name='Фотография')
    """
    Для работы с полем ImageField необходимо установить библиотеку Pillow
    """
    # group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='Students')
    # profile = models.OneToOneField(Profile, on_delete=models.CASCADE)
    # tags = models.ManyToManyField(Tag)
    #
    # STATUS_CHOICES = [
    #     ('draft', 'Draft'),
    #     ('published', 'Published'),
    # ]
    # status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    #
    # def __str__(self):
    #     return f"{self.first_name} {self.last_name}"
    #
    # class Meta:
    #     verbose_name = "студент"
    #     verbose_name_plural = "студенты"
    #     ordering = ["last_name"]
    #     db_table = "custom_table_name"

Students/forms.py
from django import forms
from .models import Student
from django.core.exceptions import ValidationError


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['first_name', 'last_name', 'year', 'email', 'enrollment_date', ]

    def __init__(self, *args, **kwargs):
        super(StudentForm, self).__init__(*args, **kwargs)

        # Настройка атрибутов виджета для поля 'first_name'
        self.fields['first_name'].widget.attrs.update({
            'class': 'form-control',  # Добавление CSS-класса для стилизации поля
            'placeholder': 'Введите имя'  # Текст подсказки внутри поля
        })

        # Настройка атрибутов виджета для поля 'last_name'
        self.fields['last_name'].widget.attrs.update({
            'class': 'form-control',  # Добавление CSS-класса для стилизации поля
            'placeholder': 'Введите фамилию'  # Текст подсказки внутри поля
        })

        # Настройка атрибутов виджета для поля 'email'
        self.fields['email'].widget.attrs.update({
            'class': 'form-control',  # Добавление CSS-класса для стилизации поля
            'placeholder': 'Введите email'  # Текст подсказки внутри поля
        })

        # Настройка атрибутов виджета для поля 'enrollment_date'
        self.fields['enrollment_date'].widget.attrs.update({
            'class': 'form-control',  # Добавление CSS-класса для стилизации поля
            'type': 'date'  # Указание типа поля как даты
        })

    def clean_email(self):
        email = self.cleaned_data.get('email')
        suffix = ('@example.com', '@gmail.com', '@mail.ru',)
        if not email.endswith(suffix):
            raise ValidationError(f'Email должен оканчиваться на {suffix}')
        return email

    def clean(self):
        cleaned_data = super().clean()
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')

        if first_name and last_name and first_name.lower() == last_name.lower():
            self.add_error('last_name', 'Имя и фамилия не могут быть одинаковыми')

Students/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView

from Students.forms import StudentForm
from Students.models import Student, MyModel


class StudentCreateView(CreateView):
    model = Student # Указываем модель, с которой будет работать это представление
    form_class = StudentForm # Указываем форму, которая будет использоваться для ввода данных
    template_name = 'Students/student_form.html' # Шаблон, который будет использоваться для отображения формы
    success_url = reverse_lazy('Students:student_list') # URL, на который будет перенаправлен пользователь после успешной отправки формы


class StudentUpdateView(UpdateView):
    model = Student
    form_class = StudentForm
    template_name = 'Students/student_form.html'
    success_url = reverse_lazy('Students:student_list')


"""ниже идут CBV контроллеры"""


class MyModelCreateView(CreateView):
    model = MyModel
    fields = ['name', 'description']
    template_name = 'Students/mymodel_form.html'
    success_url = reverse_lazy('Students:mymodel_list')

    def form_valid(self, form):
        """
        form_valid() — используется для обработки данных,
        если форма прошла валидацию.
        Этот метод вызывается после успешной валидации формы и
        сохранения данных
        """
        form.instance.created_by = self.request.user

        return super().form_valid(form)

    def form_invalid(self, form):
        """
        form_invalid() — используется для обработки данных,
        если форма не прошла валидацию.
        Этот метод вызывается при ошибках валидации формы
        """
        response = super().form_invalid(form)
        response.context_data['error_message'] = 'Please correct the errors'

        return response


class MyModelListView(ListView):
    model = MyModel
    template_name = 'Students/mymodel_list.html'
    context_object_name = 'mymodels'

    def get_queryset(self):
        """
        get_queryset() — используется для получения набора данных,
        который будет отображаться в представлении.
        Этот метод позволяет настроить выборку данных из базы данных
        """
        queryset = super().get_queryset().filter(is_active=True)
        return queryset


class MyModelDetailView(DetailView):
    model = MyModel
    template_name = 'Students/mymodel_detail.html'
    context_object_name = 'mymodel'

    def get_additional_data(self):
        return 'Это дополнительная информация'

    def get_context_data(self, **kwargs):
        """
        get_context_data() — используется для добавления данных в контекст шаблона.
        Этот метод позволяет передавать дополнительные данные в шаблон для рендеринга
        """
        context = super().get_context_data(**kwargs)
        context['additional_data'] = self.get_additional_data()
        return context

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if not obj.is_active:
            raise Http404('Object not found')
        return obj


class MyModelUpdateView(UpdateView):
    model = MyModel
    fields = ['name', 'description']
    template_name = 'Students/mymodel_form.html'
    success_url = reverse_lazy('Students:mymodel_list')


class MyModelDeleteView(DeleteView):
    model = MyModel
    template_name = 'Students/mymodel_confirm_delete.html'
    success_url = reverse_lazy('Students:mymodel_list')


"""ниже идут FBV"""


def example_view(request):
    return render(request, 'app/example.html')


def show_data(request):
    if request.method == 'GET':
        return render(request, 'app/show_data.html')


def submit_data(request):
    # request.GET   - это словари хранящие в себе GET(получить)
    # request.POST  - и POST(отправить) параметры запроса соответственно.
    if request.method == 'POST':
        return HttpResponse("Данные отправлены")


def show_item(request, item_id):
    return render(request, 'app/item.html', {'item_id': item_id})


def about(request):
    return render(request, 'Students/about.html')


def contact(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        message = request.POST.get('message')

        return HttpResponse(f'Спасибо, {name}! Сообщение получено.')
    return render(request, 'Students/contact.html')


def index(request):
    student = Student.objects.get(id=1)
    context = {
        'student_name': f"{student.first_name} {student.last_name}",
        'student_year': student.get_year_display(),
    }
    return render(request, 'Students/index.html', context=context)


def student_detail(request, student_id):
    student = Student.objects.get(id=1)
    context = {
        'student': student,
    }
    return render(request, 'Students/student_detail.html', context=context)


def student_list(request):
    students = Student.objects.all()
    context = {
        'students': students,
    }
    return render(request, 'Students/student_list.html', context)

Students/templates/Students/about.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.8">
    <title>О нас</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <h1 class="mt-5">О нас</h1>
    <p class="lead">Добро пожаловать на наш сайт! Мы — команда разработчиков из разных уголков мира, работающая над увлекательными
        проектами.</p>
</div>
<script src="/static/js/bootstrap.bundle.min.js"></script>

</body>
</html>

Students/templates/Students/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Сайт студентов{% endblock %}</title>
    <!-- Подключение Bootstrap CSS -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
{% include 'Students/header.html' %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Сайт студентов</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="#">Главная</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">О нас</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Контакты</a>
            </li>
        </ul>
    </div>
</nav>
<div class="container mt-5">
    {% block content %}{% endblock %}
</div>
<!-- Подключение Bootstrap JS -->
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>

Students/templates/Students/contact.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.8">
    <title>Контактная форма</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
<div class="container mt-5">
    <h1>Свяжитесь с нами</h1>
    <form method="post" action="">
        {% csrf_token %}
        <!--        отвечает за безопасную обработку запроса и блокирует вредоносные и опасные для целостности данных пользователя запросы-->
        <div class="mb-3">
            <label for="name" class="form-label">Ваше имя</label>
            <input type="text" class="form-control" id="name" name="name" required>
        </div>
        <div class="mb-3">
            <label for="message" class="form-label">Ваше сообщение</label>
            <textarea class="form-control" id="message" name="message" rows="5" required></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
    </form>
</div>
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Students/templates/Students/header.html
<header>
    <h1>Сайт студентов</h1>
    <p>Добро пожаловать на сайт студентов</p>
</header>

Students/templates/Students/home.html
{% extends 'base.html' %}

{% block title %}Главная страница{% endblock %}

{% block content %}
<h1>Добро пожаловать на наш сайт!</h1>
<p>Это главная страница нашего сайта.</p>
{% endblock %}

Students/templates/Students/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

Students/templates/Students/mymodel_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Форма MyModel</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1 class="mb-4">Удалить объект MyModel</h1>
        <p>Вы уверены, что хотите удалить "{{ mymodel.name }}"</p>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'Students:mymodel_list' %}">Отмена</a>
        </form>
    </div>
    <script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Students/templates/Students/mymodel_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Форма MyModel</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <h1 class="mb-4">{{ mymodel.name }}</h1>
    <p>{{ mymodel.description }}</p>
    <p>Создано: {{ mymodel.created_at }}</p>
    <p>Обновлено: {{ mymodel.updated_at }}</p>

</div>
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Students/templates/Students/mymodel_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Форма MyModel</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1 class="mb-4">Форма MyModel</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
            <a href="{% url 'Students:mymodel_list' %}">Отмена</a>
        </form>
    </div>
    <script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Students/templates/Students/mymodel_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Форма MyModel</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1 class="mb-4">Список MyModel</h1>
        <a href="{% url 'Students:mymodel_create' %}" class="btn btn-primary">Создать новый MyModel</a>
        <ul class="list-group">
            {% for mymodel in mymodels %}
            <li class="list-group-item">
                <a href="{% url 'Students:mymodel_detail' mymodel.pk %}">{{ mymodel.name }}</a>
                <a href="{% url 'Students:mymodel_update' mymodel.pk %}" class="btn btn-secondary">Редактировать</a>
                <a href="{% url 'Students:mymodel_delete' mymodel.pk %}" class="btn btn-danger">Удалить</a>
            </li>
            {% endfor %}
        </ul>

    </div>
    <script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Students/templates/Students/student_detail.html
{% extends 'Students/base.html' %}

{% block title %}Список студентов{% endblock %}

{% block content %}
{% include 'Students/header.html' %}
<h2>Детали студента</h2>
<p>Имя: {{ student.first_name }}</p>
<p>Фамилия: {{ student.last_name }}</p>
<p>Курс: {{ student.get_year_display }}</p>
{% endblock %}

Students/templates/Students/student_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Форма для студента</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1 class="mb-4">Форма для студента</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }} <!-- Отображение полей формы -->
            <button type="submit" class="btn btn-primary">Сохранить</button>
            <a href="{% url 'Students:student_list' %}">Отмена</a>
        </form>
    </div>
    <script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Students/templates/Students/student_list.html
{% extends 'Students/base.html' %}

{% block title %}Список студентов{% endblock %}

{% block content %}
{% include 'Students/header.html' %}
<h2>Список студентов</h2>
<ul class="list-group">
    {% for student in students %}
    <li class="list-group-item">
        {{ student.first_name }} {{ student.last_name }} - {{ student.year }}
    </li>
    {% endfor %}
</ul>
{% endblock %}