config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Students/', include('Students.urls', namespace='Students')),    # таким образом мы подключаем .urls с нешего приложения
    path('library/', include('library.urls', namespace='library')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

"""
Определяет маршрутизацию для вашего проекта, 
связывая URL-адреса с соответствующими контроллерами (views)
"""

library/urls.py
from django.urls import path

from library.views import BooksListView, BookDetailView, BookCreateView, BookUpdateView, BookDeleteView, \
    AuthorCreateView, AuthorUpdateView, AuthorListView

app_name = 'library'

urlpatterns = [
    path('authors/', AuthorListView.as_view(), name='authors_list'),
    path('author/new/', AuthorCreateView.as_view(), name='author_create'),
    path('author/update/<int:pk>', AuthorUpdateView.as_view(), name='author_update'),

    path('books/', BooksListView.as_view(), name='books_list'),
    path('books/<int:pk>/', BookDetailView.as_view(), name='book_detail'),
    path('books/new/', BookCreateView.as_view(), name='book_create'),
    path('books/<int:pk>/edit/', BookUpdateView.as_view(), name='book_edit'),
    path('books/<int:pk>/delete/', BookDeleteView.as_view(), name='book_delete'),


]

library/models.py
from django.db import models


class Author(models.Model):
    first_name = models.CharField(max_length=150, verbose_name='Имя')
    last_name = models.CharField(max_length=150, verbose_name='Фамилия')
    birth_date = models.DateField(verbose_name='Дата рождения')

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        verbose_name = 'автор'
        verbose_name_plural = 'авторы'
        ordering = ['last_name']


class Book(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название')
    publication_date = models.DateField(verbose_name='Дата публикации')
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='books')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'книга'
        verbose_name_plural = 'книги'
        ordering = ['title']

library/forms.py
from django import forms
from .models import Author, Book
from django.core.exceptions import ValidationError


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['first_name', 'last_name', 'birth_date']

    def __init__(self, *args, **kwargs):
        super(AuthorForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Введите имя'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Введите фамилию'})
        self.fields['birth_date'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Введите дату рождения'})

    def clean(self):
        cleaned_data = super().clean()
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')

        if Author.objects.filter(first_name=first_name, last_name=last_name).exists():
            raise ValidationError('Автор с таким именем и фамилией уже существует.')

        return cleaned_data


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'publication_date', 'author']

    def __init__(self, *args, **kwargs):
        super(BookForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Введите название книги'})
        self.fields['publication_date'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Введите дату публикации'})
        self.fields['author'].widget.attrs.update({'class': 'form-control'})

library/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from .forms import AuthorForm, BookForm
from .models import Book, Author


class AuthorListView(ListView):
    model = Author
    template_name = 'library/authors_list.html'
    context_object_name = 'authors'


class AuthorCreateView(CreateView):
    model = Author
    form_class = AuthorForm
    template_name = 'library/author_form.html'
    success_url = reverse_lazy('library:authors_list')


class AuthorUpdateView(UpdateView):
    model = Author
    form_class = AuthorForm
    template_name = 'library/author_form.html'
    success_url = reverse_lazy('library:authors_list')


class BooksListView(ListView):
    model = Book
    template_name = 'library/books_list.html'
    context_object_name = 'books'

    # def get_queryset(self):
    #     queryset = super().get_queryset()
    #     return queryset.filter(publication_date__year__gt=2000)


class BookDetailView(DetailView):
    model = Book
    template_name = 'library/book_detail.html'
    context_object_name = 'book'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author_books_count'] = Book.objects.filter(author=self.object.author).count()
        return context


class BookCreateView(CreateView):
    model = Book
    form_class = BookForm
    template_name = 'library/book_form.html'
    success_url = reverse_lazy('library:books_list')


class BookUpdateView(UpdateView):
    model = Book
    form_class = BookForm
    template_name = 'library/book_form.html'
    success_url = reverse_lazy('library:books_list')


class BookDeleteView(DeleteView):
    model = Book
    template_name = 'library/book_confirm_delete.html'
    success_url = reverse_lazy('library:books_list')

library/templates/library/author_form.html
{% extends 'library/base.html' %}

{% block title %}Добавить/Редактировать автора{% endblock %}

{% block content %}
{% include 'library/header.html' %}
<h2>Форма для автора</h2>
<form method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Сохранить</button>
    <a href="{% url 'library:authors_list' %}" class="btn btn-secondary">Отмена</a>
</form>
{% endblock %}

library/templates/library/authors_list.html
{% extends 'library/base.html' %}

{% block title %}Список авторов{% endblock %}

{% block content %}
{% include 'library/header.html' %}
<h2>Список авторов</h2>
<ul class="list-group">
    {% for author in authors %}
    <li class="list-group-item">
        {{ author.first_name }} {{ author.last_name }}
    </li>
    {% endfor %}
</ul>
{% endblock %}

library/templates/library/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Управление библиотекой{% endblock %}</title>
    <!-- Подключение Bootstrap CSS -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Библиотека</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Авторы</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Книги</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container mt-5">
        {% block content %}{% endblock %}
    </div>
    <!-- Подключение Bootstrap JS -->
    <script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

library/templates/library/book_confirm_delete.html
{% extends 'library/base.html' %}

{% block title %}Удалить книгу{% endblock %}

{% block content %}
{% include 'library/header.html' %}
<h2>Удалить книгу</h2>
<p>Вы уверены, что хотите удалить "{{ book.title }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Удалить</button>
    <a href="{% url 'library:books_list' %}" class="btn btn-secondary">Отмена</a>
</form>
{% endblock %}

library/templates/library/book_detail.html
{% extends 'library/base.html' %}

{% block title %}Детали книги{% endblock %}

{% block content %}
{% include 'library/header.html' %}
<h2>{{ book.title }}</h2>
<p>Автор: {{ book.author.first_name }} {{ book.author.last_name }}</p>
<p>Дата публикации: {{ book.publication_date|date:"d M Y" }}</p>
<a href="{% url 'library:book_edit' book.pk %}" class="btn btn-secondary">Редактировать</a>
<a href="{% url 'library:book_delete' book.pk %}" class="btn btn-danger">Удалить</a>
<a href="{% url 'library:books_list' %}" class="btn btn-primary">Вернуться к списку</a>
{% endblock %}

library/templates/library/book_form.html
{% extends 'library/base.html' %}

{% block title %}Форма книги{% endblock %}

{% block content %}
{% include 'library/header.html' %}
<h2>Форма книги</h2>
<form method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Сохранить</button>
    <a href="{% url 'library:books_list' %}" class="btn btn-secondary">Отмена</a>
</form>
{% endblock %}

library/templates/library/books_list.html
{% extends 'library/base.html' %}

{% block title %}Список книг{% endblock %}

{% block content %}
{% include 'library/header.html' %}
<h2>Список книг</h2>
<ul class="list-group">
    {% for book in books %}
    <li class="list-group-item">
        <a href="{% url 'library:book_detail' book.pk %}"> {{ book.title }} - {{ book.publication_date|date:"d M Y" }} -
            {{ book.author.first_name }} {{ book.author.last_name }} </a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

library/templates/library/header.html
<div class="header">
    <h1>Библиотека</h1>
    <nav>
        <a href="{% url 'library:books_list' %}">Список книг</a>
        <a href="{% url 'library:book_create' %}">Добавить книгу</a>
        <a href="{% url 'library:authors_list' %}">Список авторов</a>
        <a href="{% url 'library:author_create' %}">Добавить автора</a>
    </nav>
</div>
<hr>